ANOS_ESCOLARIDADE = {
    106: '1º ANO',
    107: '6º ANO',
    108: '1 ANO',
    109: '2 ANOS',
    110: '3 ANOS',
    111: '4 ANOS',
    112: '5 ANOS',
    113: '2º ANO',
    114: '3º ANO',
    115: '4º ANO',
    116: '5º ANO',
    117: '7º ANO',
    118: '8º ANO',
    119: '9º ANO',
}


UNIDADES = [
    {'unidade_id': 2, 'nome_unidade': 'EMEF ADELSON DEL SANTO'},
    {'unidade_id': 3, 'nome_unidade': 'EMEF ANGELO RECLA'},
    {'unidade_id': 4, 'nome_unidade': 'EMEF ANTÔNIO FERNANDES DE ALMEIDA'},
    {'unidade_id': 5, 'nome_unidade': 'EMEF CABOCLO BERNARDO'},
    {'unidade_id': 6, 'nome_unidade': 'EMEF CID ADALBERTO DOS REIS'},
    {'unidade_id': 7, 'nome_unidade': 'EMEF DINORAH ALMEIDA RODRIGUES'},
    {'unidade_id': 8, 'nome_unidade': 'EMEF ELZA RONI SCARPATI'},
    {'unidade_id': 9, 'nome_unidade': 'EMEF ZEFERINO BATISTA FIOROT'},
    {'unidade_id': 10, 'nome_unidade': 'EMEF JERÔNIMO MONTEIRO'},
    {'unidade_id': 11, 'nome_unidade': 'EMEF JOSÉ MODENEZE'},
    {'unidade_id': 12, 'nome_unidade': 'EMEF MANOEL MARTINS'},
    {'unidade_id': 13, 'nome_unidade': 'EMEF OROZIMBO LEITE'},
    {'unidade_id': 14, 'nome_unidade': 'EMEF PREFEITO ROBERTO CALMON'},
    {'unidade_id': 15, 'nome_unidade': 'EMEF PRESIDENTE CASTELO BRANCO'},
    {'unidade_id': 16, 'nome_unidade': 'EMEF PROFESSORA EFIGÊNIA SIZENANDO'},
    {'unidade_id': 17, 'nome_unidade': 'EMEF PROFESSORA MARIA APARECIDA LAVAGNOLI'},
    {'unidade_id': 18, 'nome_unidade': 'EMEF PROFESSORA URBANA PENHA COSTA'},
    {'unidade_id': 19, 'nome_unidade': 'EMEF PROFESSORA ELIANA CORREA PINAFO'},
    {'unidade_id': 20, 'nome_unidade': 'EMEF PROFESSORA MARIA DA PENHA PAZITO VENTURA'},
    {'unidade_id': 21, 'nome_unidade': 'EMEF ROBERTO MOREIRA'},
    {'unidade_id': 22, 'nome_unidade': 'EMEF SAMUEL BATISTA CRUZ (CAIC)'},
    {'unidade_id': 23, 'nome_unidade': 'EMEF TALMA DRUMOND PESTANA'},
    {'unidade_id': 24, 'nome_unidade': 'EMEFM MARÍLIA DE REZENDE SCARTON COUTINHO'},
    {'unidade_id': 25, 'nome_unidade': 'EUM CÓRREGO POLIDÓRIO'},
    {'unidade_id': 26, 'nome_unidade': 'EMPEF VILA BETHÂNIA'},
    {'unidade_id': 27, 'nome_unidade': 'EMPEF JOSÉ CÂNDIDO DURÃO'},
    {'unidade_id': 28, 'nome_unidade': 'EMUEF SANTA ROSA'},
    {'unidade_id': 29, 'nome_unidade': 'EMUEF ALCINA GUIMARÃES PEREIRA'},
    {'unidade_id': 30, 'nome_unidade': 'PEM AREAL'},
    {'unidade_id': 31, 'nome_unidade': 'EMUEF ARNALDO BISI'},
    {'unidade_id': 32, 'nome_unidade': 'EMUEF CAMPOS VERDES'},
    {'unidade_id': 33, 'nome_unidade': 'EMUEF CÓRREGO PIABANHA'},
    {'unidade_id': 34, 'nome_unidade': 'EMPEIPEF BIBIANA COSTA'},
    {'unidade_id': 35, 'nome_unidade': 'EMUEF PONTAL DO OURO'},
    {'unidade_id': 36, 'nome_unidade': 'EUM FAZENDA CAPIXABA'},
    {'unidade_id': 37, 'nome_unidade': 'EMUEF FAZENDA FORNACIARI'},
    {'unidade_id': 38, 'nome_unidade': 'EMUEF FAZENDA PARANINA'},
    {'unidade_id': 39, 'nome_unidade': 'EMUEF FAZENDA RIACHUELO'},
    {'unidade_id': 40, 'nome_unidade': 'EMUEF FAZENDA THESOURO'},
    {'unidade_id': 41, 'nome_unidade': 'EMUEF FAZENDA ZACARIAS'},
    {'unidade_id': 42, 'nome_unidade': 'EUM FAZENDA MARIA BONITA'},
    {'unidade_id': 43, 'nome_unidade': 'CMEIEF ALCIDES MARINATO'},
    {'unidade_id': 44, 'nome_unidade': 'CEIM ADAGMAR PINTO SANTOS'},
    {'unidade_id': 45, 'nome_unidade': 'CEIM AGNELO GUIMARÃES'},
    {'unidade_id': 46, 'nome_unidade': 'CEIM AGOSTINHO RIGONI'},
    {'unidade_id': 47, 'nome_unidade': 'CEIM ALEGRIA DO SABER'},
    {'unidade_id': 48, 'nome_unidade': 'CEIM ALFREDO CHRIST'},
    {'unidade_id': 49, 'nome_unidade': 'CEIM AMIGOS DO SABER'},
    {'unidade_id': 50, 'nome_unidade': 'CEIM ANGELINA SCANDIAN RIGONI'},
    {'unidade_id': 51, 'nome_unidade': 'CEIM ANTÔNIO APRÍGIO'},
    {'unidade_id': 52, 'nome_unidade': 'CEIM ARISTIDES PINTO CALDEIRA'},
    {'unidade_id': 53, 'nome_unidade': 'CEIM BRANCA DE NEVE'},
    {'unidade_id': 54, 'nome_unidade': 'CEIM CHAPEUZINHO VERMELHO'},
    {'unidade_id': 55, 'nome_unidade': 'CEIM CRESCER'},
    {'unidade_id': 56, 'nome_unidade': 'CEIM ENOCK DE FREITAS'},
    {'unidade_id': 57, 'nome_unidade': 'CEIM GENY RIBEIRO DE SOUZA'},
    {'unidade_id': 58, 'nome_unidade': 'CEIM JEAN CARLOS BASTOS'},
    {'unidade_id': 59, 'nome_unidade': 'CEIM JOSÉ CÂNDIDO DURÃO'},
    {'unidade_id': 60, 'nome_unidade': 'CEIM JOSÉ ELIAS'},
    {'unidade_id': 61, 'nome_unidade': 'CEIM LEODOVICO DONATELLI'},
    {'unidade_id': 62, 'nome_unidade': 'CEIM MANOEL FARIAS DE SOUZA'},
    {'unidade_id': 63, 'nome_unidade': 'CEIM PERPÉTUA MARIA DOS ANJOS'},
    {'unidade_id': 64, 'nome_unidade': 'CEIM PETER PAN'},
    {'unidade_id': 65, 'nome_unidade': 'CEIM REINO MÁGICO'},
    {'unidade_id': 66, 'nome_unidade': 'CEIM OLGA BORTOT MOLINA'},
    {'unidade_id': 67, 'nome_unidade': 'CEIM ROTARY CLUBE "ANSELMO RUY BOBBIO"'},
    {'unidade_id': 68, 'nome_unidade': 'CEIM SANTA RITA DE CÁSSIA'},
    {'unidade_id': 69, 'nome_unidade': 'CEIM SEBASTIÃO JUSTINO FURTADO'},
    {'unidade_id': 70, 'nome_unidade': 'CEIM VALDIR GABRIEL MARIM'},
    {'unidade_id': 71, 'nome_unidade': 'CEIM VILA REGÊNCIA'},
    {'unidade_id': 72, 'nome_unidade': 'CEIM VOVÓ AURORA'},
    {'unidade_id': 73, 'nome_unidade': 'CEIM WENDERSON NICO DE FREITAS'},
    {'unidade_id': 74, 'nome_unidade': 'CEIM ILÍDIA ROSA DE ALMEIDA DOS SANTOS'},
    {'unidade_id': 75, 'nome_unidade': 'EMPEI GERÔNCIO FRANCISCO'},
    {'unidade_id': 76, 'nome_unidade': 'CEIM DOCE MEL'},
    {'unidade_id': 77, 'nome_unidade': 'EMPEIPEF AREAL'},
    {'unidade_id': 78, 'nome_unidade': 'EMPEI PAULO DAMIÃO TRISTÃO PURINHA'},
    {'unidade_id': 79, 'nome_unidade': 'EMPEIUEF EMA SARTÓRIO BIANCARDI'},
    {'unidade_id': 80, 'nome_unidade': 'EMUEF FAZENDA POÇÃO'},
    {'unidade_id': 81, 'nome_unidade': 'EMPEIUEF RIO QUARTEL'},
    {'unidade_id': 82, 'nome_unidade': 'EMPEIPEF CÓRREGO JAPIRA'},
    {'unidade_id': 83, 'nome_unidade': 'EMUEF FAZENDA TRÊS MARIAS'},
    {'unidade_id': 84, 'nome_unidade': 'EMUEF NOSSA SENHORA DO BOM PARTO'},
    {'unidade_id': 85, 'nome_unidade': 'EMUEF SANTO HILÁRIO'},
    {'unidade_id': 86, 'nome_unidade': 'EMUEF SANTA LUZIA'},
    {'unidade_id': 87, 'nome_unidade': 'EMUEF LAGOA DAS PALMAS'},
    {'unidade_id': 88, 'nome_unidade': 'EMPEIPEF CÓRREGO SÃO PEDRO'},
    {'unidade_id': 89, 'nome_unidade': 'EEUEF FAZENDA RIACHUELO'},
    {'unidade_id': 90, 'nome_unidade': 'EMPEF PATRIMÔNIO HUMAITÁ'},
    {'unidade_id': 91, 'nome_unidade': 'EMUEF FRANCISCO POLESE PRIMO'},
    {'unidade_id': 92, 'nome_unidade': 'EUM JATAIPEBA'},
    {'unidade_id': 93, 'nome_unidade': 'EMUEF CÓRREGO DO MEIO'},
    {'unidade_id': 94, 'nome_unidade': 'EMPEF PALHAL'},
    {'unidade_id': 95, 'nome_unidade': 'EMPEIPEF BOA ESPERANÇA'},
    {'unidade_id': 96, 'nome_unidade': 'EMPEIPEF FLORENTINO RODRIGUES BATISTA'},
    {'unidade_id': 97, 'nome_unidade': 'EMPEIPEF BANANAL DO SUL'},
    {'unidade_id': 98, 'nome_unidade': 'EMPEIUEF TERRA ALTA'},
    {'unidade_id': 99, 'nome_unidade': 'EMUEF SÃO JOÃO DA TERRA ALTA'},
    {'unidade_id': 100, 'nome_unidade': 'EMPEIPEF CÓRREGO DR. JONES'},
    {'unidade_id': 101, 'nome_unidade': 'EMEF MARIA SOUZA MATIAS'},
    {'unidade_id': 102, 'nome_unidade': 'CEIM MARIANA BATISTA POMPERMAYER'},
    {'unidade_id': 103, 'nome_unidade': 'EMUEF CABECEIRA DO PAU GROSSO'},
    {'unidade_id': 104, 'nome_unidade': 'EMUEF SÃO JUDAS TADEU'},
    {'unidade_id': 105, 'nome_unidade': 'CEIM GIOVANI PAULO SALVADOR MEIRA'},
    {'unidade_id': 106, 'nome_unidade': 'PEM CRIANÇA FELIZ'},
    {'unidade_id': 107, 'nome_unidade': 'PEM ESPAÇO CRIATIVO'},
    {'unidade_id': 108, 'nome_unidade': 'PEM RAIO DE LUZ'},
    {'unidade_id': 109, 'nome_unidade': 'PEM RIO DAS PALMAS'},
    {'unidade_id': 110, 'nome_unidade': 'PEM PEROBAS'},
    {'unidade_id': 111, 'nome_unidade': 'PEM SANTA ROSA'},
    {'unidade_id': 112, 'nome_unidade': 'PEM CÓRREGO DR. JONES'},
    {'unidade_id': 113, 'nome_unidade': 'PEM PEDRO HENRIQUE SESANA'},
    {'unidade_id': 114, 'nome_unidade': 'EMPEI SÃO CRISTÓVÃO'},
    {'unidade_id': 115, 'nome_unidade': 'CEIM VALDIR GABRIEL MARIM (EXTENSÃO)'},
    {'unidade_id': 116, 'nome_unidade': 'CEIM CHAPEUZINHO VERMELHO (EXTENSÃO)'},
    {'unidade_id': 117, 'nome_unidade': 'CID'},
    {'unidade_id': 118, 'nome_unidade': 'EMEF AUTO GUIMARÃES E SOUZA'},
    {'unidade_id': 119, 'nome_unidade': 'EMEF LUIZ DE CAMÕES'},
    {'unidade_id': 120, 'nome_unidade': 'EMEF CELINA COUTINHO NUNES'},
    {'unidade_id': 121, 'nome_unidade': 'CEIM RIO DOCE'},
    {'unidade_id': 122, 'nome_unidade': 'PEM CRIANÇA FELIZ'},
    {'unidade_id': 123, 'nome_unidade': 'RAIO DE LUZ'},
    {'unidade_id': 124, 'nome_unidade': 'EMUEF PAULO ANDRÉ DE LIMA'},
    {'unidade_id': 125, 'nome_unidade': 'CEIM THEREZINHA DURÃO COSTA'},
    {'unidade_id': 126, 'nome_unidade': 'CEIM JOCAFE'},
    {'unidade_id': 127, 'nome_unidade': 'CEIM PROFESSORA ANGELA MARIA GIOVANELLI'},
    {'unidade_id': 128, 'nome_unidade': 'CMEIEFTI PALMITAL'},
    {'unidade_id': 129, 'nome_unidade': 'CEIM JOELMA ROCHA VIEIRA'},
    {'unidade_id': 130, 'nome_unidade': 'EMEF NOSSA SENHORA DA CONCEIÇÃO'},
    {'unidade_id': 131, 'nome_unidade': 'EMEF PROFESSOR JOCIVAL MARCHIORI'},
    {'unidade_id': 132, 'nome_unidade': 'ESCOLA MATA DO CACAU'},
    {'unidade_id': 133, 'nome_unidade': 'EMEFTI EVALDO SOELLA'}
]

CONSULTAS = [ 
    {
        'unidade_id': unidade['unidade_id'],
        'nome_unidade': unidade['nome_unidade'],
        'ano_de_escolaridade_id': ano_id,
        'nome_ano': nome_ano
    }
    for unidade in UNIDADES
    for ano_id, nome_ano in ANOS_ESCOLARIDADE.items()
]
   

BASE_URL = 'https://linhares.sisp.com.br/lista-publica/buscar-inscricoes-ajax'

OUTPUT_DIR = 'output'